//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestForEventRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEventSetRegister
    {
        public int fEventRegisterId { get; set; }
        public Nullable<int> fEventId { get; set; }
        public Nullable<int> fUserId { get; set; }
        public Nullable<int> fnumAttendPeople { get; set; }
        public Nullable<int> ferName { get; set; }
        public Nullable<int> ferPhone { get; set; }
        public Nullable<int> ferEmail { get; set; }
        public Nullable<int> ferGender { get; set; }
        public Nullable<int> ferBirthday { get; set; }
        public Nullable<int> ferIdentity { get; set; }
        public Nullable<int> ferOccupation { get; set; }
        public Nullable<int> ferVeganOrNot { get; set; }
        public Nullable<int> ferOtherColumn1 { get; set; }
        public string ferOtherColumn2 { get; set; }
        public string ferOtherColumn3 { get; set; }
        public string ferOtherColumn4 { get; set; }
        public string ferOtherColumn5 { get; set; }
    
        public virtual tEvent tEvent { get; set; }
    }
}
